[workspace]
authors = ["Jaeyong"]
channels = ["conda-forge", "bioconda"]
name = "gem"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
diamond = ">=2.1.15,<3"
pyscipopt = ">=5.6.0,<6"
pandas = ">=2.0.0,<3"
numpy = ">=1.24.0,<2"
scipy = ">=1.10.0,<2"
matplotlib = ">=3.7.0,<4"
seaborn = ">=0.12.0,<1"
jupyter = ">=1.0.0,<2"
jupyterlab = ">=4.0.0,<5"
tqdm = ">=4.65.0,<5"

[pypi-dependencies]
cobra = ">=0.30.0, <0.31"
carveme = ">=1.6.6, <2"
memote = ">=0.17.0, <0.18"
